title: Pushy Clipboard
description: A cross platform clipboard manager with push notifications
theme: jekyll-theme-cayman
show_downloads: "false"
repository: Pushy-Clipboard/Pushy-Clipboard.github.io
